name: "GAC"
version: "${pom.version}"
api: ["9.9.9"]
main: cz.creeperface.nukkit.gac.GTAnticheat
author: "CreeperFace"
description: "Basic AntiCheat plugin for Nukkit"
softdepend: ["SynapseAPI"]
depend: ["KotlinLib"]